version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    links:
      - mysql
      #- postgres
      #- mail
      #- solr
      #- elasticsearch
      #- redis
      #- memcached
      #- ftp
    ports:
      - "8000:80"
      - "8443:443"
      - "10022:22"
    restart: always
    volumes:
      - ./app/:/app/
    env_file:
      - etc/base.env
      - etc/production.env

  #######################################
  # MySQL server
  #######################################
  mysql:
    build:
      context: docker/mysql/
      #dockerfile: MySQL-5.5.Dockerfile
      dockerfile: MySQL-5.6.Dockerfile
      #dockerfile: MySQL-5.7.Dockerfile
      #dockerfile: MariaDB-5.5.Dockerfile
      #dockerfile: MariaDB-10.Dockerfile
      #dockerfile: Percona-5.5.Dockerfile
      #dockerfile: Percona-5.6.Dockerfile
      #dockerfile: Percona-5.7.Dockerfile
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - etc/base.env
      - etc/production.env

  #######################################
  # PostgreSQL server
  #######################################
  #postgres:
  #  build:
  #    context: docker/postgres/
  #    dockerfile: Postgres-9.4.Dockerfile
  #    dockerfile: Postgres-9.5.Dockerfile
  #  ports:
  #    - 15432:5432
  #  restart: always
  #  volumes:
  #    - solr:/opt/solr/server/solr/data
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

  #######################################
  # Solr server
  #######################################
  #solr:
  #  image: webdevops/typo3-solr:6.0
  #  image: webdevops/typo3-solr:5.0
  #  image: webdevops/typo3-solr:4.0
  #  image: webdevops/typo3-solr:3.1
  #  ports:
  #    - 18983:8983
  #  restart: always
  #  volumes:
  #    - solr:/opt/solr/server/solr/data
  #  environment:
  #    - SOLR_STORAGE=/opt/solr/server/solr/data
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

  #######################################
  # Elasticsearch
  #######################################
  #elasticsearch:
  #  build:
  #    context: docker/elasticsearch/
  #  ports:
  #    - 19200:9200
  #    - 19300:9300
  #  restart: always
  #  volumes:
  #    - elasticsearch:/usr/share/elasticsearch/data
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

  #######################################
  # Redis
  #######################################
  #redis:
  #  build:
  #    context: docker/redis/
  #  restart: always
  #  volumes:
  #    - redis:/data
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

  #######################################
  # Memcached
  #######################################
  #memcached:
  #  build:
  #    context: docker/memcached/
  #  restart: always
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

  #######################################
  # FTP (vsftpd)
  #######################################
  #ftp:
  #  build:
  #    context: docker/vsftp/
  #  restart: always
  #  volumes:
  #    - ./:/application/
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

volumes:
  mysql:
  postgres:
  solr:
  elasticsearch:
  redis:
  phpmyadmin:
